
class SetupActionID
{
    static PERFORM_SIMULATIONS = "SETUP.PERFORM_SIMULATIONS";
    static NEXT_EXAMPLE = "SETUP.NEXT_EXAMPLE";
    static PREVIOUS_EXAMPLE = "SETUP.PREVIOUS_EXAMPLE";
    static TOGGLE_MULIGAN_ON_POOR = "SETUP.TOGGLE_MULIGAN_ON_POOR";
    static TOGGLE_MULIGAN_WITHOUT_KEY = "SETUP.TOGGLE_MULIGAN_WITHOUT_KEY";
    static TOGGLE_MULIGAN_IF_NOT_GREAT = "SETUP.TOGGLE_MULIGAN_IF_NOT_GREAT";
    static TEST = "TEST";
}

export = SetupActionID;
