
class SetupActionID
{
    static PERFORM_SIMULATIONS = "SETUP.PERFORM_SIMULATIONS";
    static NEXT_EXAMPLE = "SETUP.NEXT_EXAMPLE";
    static PREVIOUS_EXAMPLE = "SETUP.PREVIOUS_EXAMPLE";
    static TOGGLE_MULIGAN_ON_POOR = "SETUP.TOGGLE_MULIGAN_ON_POOR";
    static TOGGLE_MULIGAN_WITHOUT_KEY = "SETUP.TOGGLE_MULIGAN_WITHOUT_KEY";
    static TOGGLE_REQUIRE_ONE_CHARACTER = "SETUP.TOGGLE_REQUIRE_ONE_CHARACTER";
    static TOGGLE_MULLIGAN_WITHOUT_ECON = "SETUP.TOGGLE_MULLIGAN_WITHOUT_ECON";
    static TOGGLE_FAVOR_ECON = "SETUP.TOGGLE_FAVOR_ECON";
    static TOGGLE_REQUIRE_ECON = "SETUP.TOGGLE_REQUIRE_ECON";
    static SET_POOR_CARDS = "SETUP.SET_POOR_CARDS";
    static SET_MINIMUM_CARDS = "SETUP.SET_MINIMUM_CARDS";
    static TOGGLE_REQUIRE_FOUR_COST_CHARACTER = "SETUP.TOGGLE_REQUIRE_FOUR_COST_CHARACTER";
    static TEST = "TEST";
}

export = SetupActionID;
